services:

  master:
    image: bitnami/postgresql:latest
    container_name: master_db
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_WRITE_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_WRITE_USER_PASSWORD}
      - POSTGRESQL_DATABASE=OnlineJudgeMasterDB
    ports:
      - 5432:5432
    networks:
      - pg_network
    volumes:
      - master_db_data:/bitnami/postgresql
    
  slave:
    image: bitnami/postgresql:latest
    container_name: slave_db 
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=${POSTGRESQL_READ_USER_PASSWORD}
    depends_on:
      - master
    ports:
      - 5431:5432
    networks:
      - pg_network
    volumes:
      - slave_db_data:/bitnami/postgresql
    
  minio:
    image: minio/minio:latest
    container_name: minio_storage
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    
  db-service:
    build: ./db-service
    container_name: db-service
    environment:
      - DB_WRITE_HOST=${DB_WRITE_HOST}
      - DB_READ_HOST=${DB_READ_HOST}
      - POSTGRESQL_WRITE_USER=${POSTGRESQL_WRITE_USER}
      - POSTGRESQL_READ_USER=${POSTGRESQL_READ_USER}
      - POSTGRESQL_WRITE_USER_PASSWORD=${POSTGRESQL_WRITE_USER_PASSWORD}
      - POSTGRESQL_READ_USER_PASSWORD=${POSTGRESQL_READ_USER_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4000:4000
    depends_on:
      - master
      - slave
    networks:
      - pg_network

networks:
  pg_network:

volumes:
  master_db_data:
  slave_db_data:
  minio_data: